// Free-to-use audio samples from various public domain / CC0 sources (Pixabay, Free Music Archive)
export const TRACKS = [
  {
    id: 1,
    title: "Neon City Lights",
    artist: "Neon Drift",
    album: "Midnight Pulse",
    cover: "https://picsum.photos/seed/album1/200",
    audio: "https://cdn.pixabay.com/audio/2023/06/19/audio_6e01c30aaa.mp3",
    duration: 150,
  },
  {
    id: 2,
    title: "Pulse Drive",
    artist: "Neon Drift",
    album: "Midnight Pulse",
    cover: "https://picsum.photos/seed/album1/200",
    audio: "https://cdn.pixabay.com/audio/2022/11/22/audio_febc508520.mp3",
    duration: 135,
  },
  {
    id: 3,
    title: "Chrome Wave",
    artist: "Neon Drift",
    album: "Chrome Dreams",
    cover: "https://picsum.photos/seed/album2/200",
    audio: "https://cdn.pixabay.com/audio/2023/03/09/audio_550d815fa5.mp3",
    duration: 165,
  },
  {
    id: 4,
    title: "Afternoon Drift",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://cdn.pixabay.com/audio/2022/10/31/audio_b5a0e90e14.mp3",
    duration: 190,
  },
  {
    id: 5,
    title: "Soft Rain",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://cdn.pixabay.com/audio/2023/01/27/audio_4991b8552f.mp3",
    duration: 175,
  },
  {
    id: 6,
    title: "Static Rush",
    artist: "Void Runner",
    album: "Static Field",
    cover: "https://picsum.photos/seed/album4/200",
    audio: "https://cdn.pixabay.com/audio/2022/12/19/audio_a15e5e8b29.mp3",
    duration: 160,
  },
  {
    id: 7,
    title: "Digital Ghost",
    artist: "Void Runner",
    album: "Static Field",
    cover: "https://picsum.photos/seed/album4/200",
    audio: "https://cdn.pixabay.com/audio/2023/02/14/audio_677b9fc699.mp3",
    duration: 180,
  },
  {
    id: 8,
    title: "Midnight Echo",
    artist: "Neon Drift",
    album: "Chrome Dreams",
    cover: "https://picsum.photos/seed/album2/200",
    audio: "https://cdn.pixabay.com/audio/2022/08/02/audio_884fe92c21.mp3",
    duration: 145,
  },
  {
    id: 9,
    title: "Lo-fi Sunday",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://cdn.pixabay.com/audio/2022/09/13/audio_29c5f9af01.mp3",
    duration: 200,
  },
];