export const ARTISTS = [
  {
    id: 1,
    name: "Neon Drift",
    genre: "Synthwave",
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=neon&backgroundColor=0f0035",
    albums: [
      { id: 1, title: "Midnight Pulse", cover: "https://picsum.photos/seed/album1/200", year: 2023 },
      { id: 2, title: "Chrome Dreams", cover: "https://picsum.photos/seed/album2/200", year: 2022 },
    ],
  },
  {
    id: 2,
    name: "Solar Haze",
    genre: "Lo-fi",
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=solar&backgroundColor=1a0a2e",
    albums: [
      { id: 3, title: "Lazy Afternoons", cover: "https://picsum.photos/seed/album3/200", year: 2024 },
    ],
  },
  {
    id: 3,
    name: "Void Runner",
    genre: "Electronic",
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=void&backgroundColor=001122",
    albums: [
      { id: 4, title: "Static Field", cover: "https://picsum.photos/seed/album4/200", year: 2023 },
    ],
  },
];

export const TRACKS = [
  {
    id: 1,
    title: "Neon City Lights",
    artist: "Neon Drift",
    album: "Midnight Pulse",
    cover: "https://picsum.photos/seed/album1/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: 2,
    title: "Pulse Drive",
    artist: "Neon Drift",
    album: "Midnight Pulse",
    cover: "https://picsum.photos/seed/album1/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: 3,
    title: "Chrome Wave",
    artist: "Neon Drift",
    album: "Chrome Dreams",
    cover: "https://picsum.photos/seed/album2/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: 4,
    title: "Afternoon Drift",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: 5,
    title: "Soft Rain",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: 6,
    title: "Static Rush",
    artist: "Void Runner",
    album: "Static Field",
    cover: "https://picsum.photos/seed/album4/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: 7,
    title: "Digital Ghost",
    artist: "Void Runner",
    album: "Static Field",
    cover: "https://picsum.photos/seed/album4/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: 8,
    title: "Midnight Echo",
    artist: "Neon Drift",
    album: "Chrome Dreams",
    cover: "https://picsum.photos/seed/album2/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: 9,
    title: "Lo-fi Sunday",
    artist: "Solar Haze",
    album: "Lazy Afternoons",
    cover: "https://picsum.photos/seed/album3/200",
    audio: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  },
];
